pull_request_rules:
  - name: remove outdated reviews for non-core authors
    conditions:
      - base=master
      - author!=@mozilla/application-services
    actions:
      dismiss_reviews:
        message: The pull request has been modified, dismissing previous reviews.
      label:
        remove:
          - checkin-needed
  - name: automatic merge for master
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=checkin-needed
      - "status-success=android-build-pr"
      - "status-success=lint-detekt"
      - "status-success=lint-ktlint"
      - "status-success=ci/circleci: Check Protobuf files are up-to-date"
      - "status-success=ci/circleci: Check Rust dependencies"
      - "status-success=ci/circleci: Check Rust formatting"
      - "status-success=ci/circleci: Check Swift formatting"
      - "status-success=ci/circleci: Lint Bash scripts"
      - "status-success=ci/circleci: Lint Rust with clippy"
      - "status-success=ci/circleci: Rust benchmarks"
      - "status-success=ci/circleci: Rust tests"
      - "status-success=ci/circleci: Sync integration tests"
      - "status-success=ci/circleci: iOS build and test"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
  # Copy pasta of above, with different checks.
  - name: automatic merge for master (CI FULL)
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=checkin-needed
      - "status-success=module-build-logins"
      - "status-success=module-build-httpconfig"
      - "status-success=module-build-full-megazord"
      - "status-success=module-build-tabs"
      - "status-success=module-build-lockbox-megazord"
      - "status-success=module-build-rustlog"
      - "status-success=module-build-places"
      - "status-success=module-build-sync15"
      - "status-success=module-build-syncmanager"
      - "status-success=module-build-fxaclient"
      - "status-success=module-build-push"
      - "status-success=module-build-native-support"
      - "status-success=lint-detekt"
      - "status-success=lint-ktlint"
      - "status-success=ci/circleci: Check Protobuf files are up-to-date"
      - "status-success=ci/circleci: Check Rust dependencies"
      - "status-success=ci/circleci: Check Rust formatting"
      - "status-success=ci/circleci: Check Swift formatting"
      - "status-success=ci/circleci: Lint Bash scripts"
      - "status-success=ci/circleci: Lint Rust with clippy"
      - "status-success=ci/circleci: Rust benchmarks"
      - "status-success=ci/circleci: Rust tests"
      - "status-success=ci/circleci: Sync integration tests"
      - "status-success=ci/circleci: iOS build and test"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
  - name: automatic merge for master (CI SKIP)
    conditions:
      - title~=\[ci skip\]
      - "#approved-reviews-by>=1"
      - base=master
      - label=checkin-needed
      - "status-success=ci/circleci: Check Protobuf files are up-to-date"
      - "status-success=ci/circleci: Check Rust dependencies"
      - "status-success=ci/circleci: Check Rust formatting"
      - "status-success=ci/circleci: Check Swift formatting"
      - "status-success=ci/circleci: Lint Bash scripts"
      - "status-success=ci/circleci: Lint Rust with clippy"
      - "status-success=ci/circleci: Rust benchmarks"
      - "status-success=ci/circleci: Rust tests"
      - "status-success=ci/circleci: Sync integration tests"
      - "status-success=ci/circleci: iOS build and test"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
